13/03/2020 13:22:13,487 ERROR L2ScriptEngineManager:657 - Failed executing script: D:\Company\GitRepo\L2Epic\L2Epic\Development\Deployemnt\gameserver\data\scripts\quests\255_Tutorial\__init__.py. See __init__.py.error.LOGGER for details.
13/03/2020 15:00:03,951 FATAL GameServer:618 - Failed to open server socket. Reason: 
java.net.BindException: Address already in use: bind
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:469)
	at java.base/sun.nio.ch.Net.bind(Net.java:458)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:220)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:88)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
	at com.l2jfrozen.netcore.SelectorThread.openServerSocket(SelectorThread.java:98)
	at com.l2jfrozen.gameserver.GameServer.main(GameServer.java:609)
13/03/2020 17:16:20,229 ERROR Quest:816 - D:\Company\GitRepo\L2Epic\L2Epic\Development\Deployemnt\gameserver\data\scripts\quests\255_Tutorial\__init__.py
Traceback (innermost last):
  File "__init__.py", line 347, in onAdvEvent
UnboundLocalError: local: 'event_id'

	at org.python.core.Py.UnboundLocalError(Unknown Source)
	at org.python.core.PyFrame.getlocal(Unknown Source)
	at org.python.core.PyFrame.getlocal(Unknown Source)
	at org.python.pycode._pyx210.onAdvEvent$4(__init__.py:347)
	at org.python.pycode._pyx210.call_function(__init__.py)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyTableCode.call(Unknown Source)
	at org.python.core.PyFunction.__call__(Unknown Source)
	at org.python.core.PyMethod.__call__(Unknown Source)
	at org.python.core.PyObject.__call__(Unknown Source)
	at org.python.core.PyObject._jcallexc(Unknown Source)
	at org.python.core.PyObject._jcall(Unknown Source)
	at org.python.proxies.main$Quest$208.onAdvEvent(Unknown Source)
	at com.l2jfrozen.gameserver.model.quest.Quest.notifyEvent(Quest.java:525)
	at com.l2jfrozen.gameserver.model.actor.stat.PcStat.addLevel(PcStat.java:188)
	at com.l2jfrozen.gameserver.model.actor.stat.PlayableStat.addExp(PlayableStat.java:45)
	at com.l2jfrozen.gameserver.model.actor.stat.PcStat.addExp(PcStat.java:43)
	at com.l2jfrozen.gameserver.model.actor.stat.PlayableStat.addExpAndSp(PlayableStat.java:88)
	at com.l2jfrozen.gameserver.model.actor.stat.PcStat.addExpAndSp(PcStat.java:122)
	at com.l2jfrozen.gameserver.model.actor.instance.L2PcInstance.addExpAndSp(L2PcInstance.java:13907)
	at com.l2jfrozen.gameserver.model.L2Attackable.calculateRewards(L2Attackable.java:652)
	at com.l2jfrozen.gameserver.model.L2Character.doDie(L2Character.java:2194)
	at com.l2jfrozen.gameserver.model.actor.instance.L2NpcInstance.doDie(L2NpcInstance.java:3017)
	at com.l2jfrozen.gameserver.model.L2Attackable.doDie(L2Attackable.java:399)
	at com.l2jfrozen.gameserver.model.actor.instance.L2MonsterInstance.doDie(L2MonsterInstance.java:231)
	at com.l2jfrozen.gameserver.model.actor.status.CharStatus.reduceHp(CharStatus.java:251)
	at com.l2jfrozen.gameserver.model.actor.status.NpcStatus.reduceHp(NpcStatus.java:33)
	at com.l2jfrozen.gameserver.model.L2Character.reduceCurrentHp(L2Character.java:10073)
	at com.l2jfrozen.gameserver.model.L2Attackable.reduceCurrentHp(L2Attackable.java:369)
	at com.l2jfrozen.gameserver.model.L2Attackable.reduceCurrentHp(L2Attackable.java:289)
	at com.l2jfrozen.gameserver.model.L2Character.onHitTimer(L2Character.java:7049)
	at com.l2jfrozen.gameserver.model.L2Character$HitTask.run(L2Character.java:3186)
	at com.l2jfrozen.gameserver.thread.ThreadPoolManager$RunnableWrapper.run(ThreadPoolManager.java:71)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
13/03/2020 17:52:37,480 ERROR L2Character:9293 - L2PcInstance.storeEffect: Could not store char effect data into character_skill_effects
java.sql.BatchUpdateException: (conn=9429) Duplicate entry '268477964-317-0' for key 'PRIMARY'
	at org.mariadb.jdbc.MariaDbStatement.executeBatchExceptionEpilogue(MariaDbStatement.java:309)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeBatch(ClientSidePreparedStatement.java:293)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at com.l2jfrozen.gameserver.model.actor.instance.L2PcInstance.storeEffect(L2PcInstance.java:9286)
	at com.l2jfrozen.gameserver.model.actor.instance.L2PcInstance.store(L2PcInstance.java:9031)
	at com.l2jfrozen.gameserver.model.actor.instance.L2PcInstance.store(L2PcInstance.java:9045)
	at com.l2jfrozen.gameserver.network.clientpackets.RequestRestart.runImpl(RequestRestart.java:166)
	at com.l2jfrozen.gameserver.network.clientpackets.L2GameClientPacket.run(L2GameClientPacket.java:67)
	at com.l2jfrozen.gameserver.network.L2GameClient.run(L2GameClient.java:1097)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=9429) Duplicate entry '268477964-317-0' for key 'PRIMARY'
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:236)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:164)
	at org.mariadb.jdbc.MariaDbStatement.executeBatchExceptionEpilogue(MariaDbStatement.java:305)
	... 12 more
Caused by: java.sql.SQLException: Duplicate entry '268477964-317-0' for key 'PRIMARY'
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1599)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1461)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1424)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeBatchRewrite(AbstractQueryProtocol.java:889)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeBatchClient(AbstractQueryProtocol.java:323)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternalBatch(ClientSidePreparedStatement.java:362)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeBatch(ClientSidePreparedStatement.java:288)
	... 11 more
13/03/2020 17:53:39,097 ERROR L2Character:9293 - L2PcInstance.storeEffect: Could not store char effect data into character_skill_effects
java.sql.BatchUpdateException: (conn=9429) Duplicate entry '268477964-317-0' for key 'PRIMARY'
	at org.mariadb.jdbc.MariaDbStatement.executeBatchExceptionEpilogue(MariaDbStatement.java:309)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeBatch(ClientSidePreparedStatement.java:293)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at com.l2jfrozen.gameserver.model.actor.instance.L2PcInstance.storeEffect(L2PcInstance.java:9286)
	at com.l2jfrozen.gameserver.model.actor.instance.L2PcInstance.store(L2PcInstance.java:9031)
	at com.l2jfrozen.gameserver.model.actor.instance.L2PcInstance.store(L2PcInstance.java:9045)
	at com.l2jfrozen.gameserver.network.clientpackets.RequestRestart.runImpl(RequestRestart.java:166)
	at com.l2jfrozen.gameserver.network.clientpackets.L2GameClientPacket.run(L2GameClientPacket.java:67)
	at com.l2jfrozen.gameserver.network.L2GameClient.run(L2GameClient.java:1097)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=9429) Duplicate entry '268477964-317-0' for key 'PRIMARY'
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:236)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:164)
	at org.mariadb.jdbc.MariaDbStatement.executeBatchExceptionEpilogue(MariaDbStatement.java:305)
	... 12 more
Caused by: java.sql.SQLException: Duplicate entry '268477964-317-0' for key 'PRIMARY'
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1599)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1461)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1424)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeBatchRewrite(AbstractQueryProtocol.java:889)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeBatchClient(AbstractQueryProtocol.java:323)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternalBatch(ClientSidePreparedStatement.java:362)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeBatch(ClientSidePreparedStatement.java:288)
	... 11 more
